### PR TITLE
Use new Google Photos API and remove unsupported functions.

### PR DESCRIPTION
**Pull request by stanaka**
Replace obsolete Picasa API with new [Google Photos API](https://developers.google.com/photos/).

Google Photos API is currently developer preview and supports only limited functions. I removed following functions for the time being.
* Update an album name
* Remove/Update photos 
  * If you modify a photo and try to re-publish it, both old and new ones are exist in a album.
  * Even if you remove a photo in Lightroom Collection and try to re-publish it, the photo remains in the album.

### CODE REVIEW

**Comment by stanaka** [comment]
@mturilin The main reason of this move is that Picasa Web Album Data API is getting broken. 

They have already stopped to support mutation operations ( https://groups.google.com/forum/#!topic/Google-Picasa-Data-API/7A3uDiiPKI0 ). This means I'm just going to disable features which have been already almost broken.

**Comment by chibiegg** [comment]
This plug-in is very useful.
This PR is very important to keep using, so I want you to merge.

**Comment by N6REJ** [comment]
@chibiegg can't merge something that has conflicts.

**Comment by chibiegg** [comment]
@N6REJ I know it. But, I have no permission to resolve conflicts of this branch.
I confirmed that it works in rebasing branch. ( https://github.com/chibiegg/lightroom-google-photo-plugin/tree/new-api )

**Comment by stanaka** [comment]
@chibiegg @N6REJ Sorry for the delay. It's now merged!

**Pull request merged**
